coding_task:
  description: >
    Write python code for the assignment {assignment} and also execute the code to get an output
  expected_output: >
    The python code for the assignment {assignment} and the output of the code
  agent: python_developer
  output_file: output/code.py
